import type { Product } from './cart-context'

export const products: Product[] = [
  // Protein Bars
  {
    id: 'bar-1',
    name: 'Chocolate Fudge Brownie',
    price: 29.99,
    image: '/products/bar-chocolate.jpg',
    category: 'protein-bars',
    flavor: 'Chocolate Fudge',
    rating: 4.9,
    reviews: 2847,
    badge: 'Best Seller',
    description: '20g protein, 1g sugar. Rich chocolate brownie flavor with a fudgy center.',
  },
  {
    id: 'bar-2',
    name: 'Salted Caramel Crunch',
    price: 29.99,
    image: '/products/bar-caramel.jpg',
    category: 'protein-bars',
    flavor: 'Salted Caramel',
    rating: 4.8,
    reviews: 1923,
    badge: 'New',
    description: '20g protein, low sugar. Sweet and salty perfection with a satisfying crunch.',
  },
  {
    id: 'bar-3',
    name: 'Peanut Butter Blast',
    price: 29.99,
    image: '/products/bar-peanut.jpg',
    category: 'protein-bars',
    flavor: 'Peanut Butter',
    rating: 4.7,
    reviews: 1654,
    description: '22g protein per bar. Creamy peanut butter with real peanut pieces.',
  },
  {
    id: 'bar-4',
    name: 'Cookie Dough Delight',
    price: 29.99,
    image: '/products/bar-cookie.jpg',
    category: 'protein-bars',
    flavor: 'Cookie Dough',
    rating: 4.8,
    reviews: 1432,
    description: '20g protein, guilt-free indulgence. Tastes like raw cookie dough.',
  },
  {
    id: 'bar-5',
    name: 'Variety Pack - 12 Bars',
    price: 34.99,
    image: '/products/bar-variety.jpg',
    category: 'protein-bars',
    flavor: 'Mixed Flavors',
    rating: 4.9,
    reviews: 3241,
    badge: 'Best Value',
    description: 'Try all our flavors! 3 of each: Chocolate, Caramel, Peanut Butter, Cookie Dough.',
  },

  // Protein Powder
  {
    id: 'powder-1',
    name: 'Whey Isolate - Vanilla',
    price: 54.99,
    image: '/products/powder-vanilla.jpg',
    category: 'protein-powder',
    flavor: 'Vanilla Bean',
    weight: '2 lbs',
    rating: 4.9,
    reviews: 4521,
    badge: 'Top Rated',
    description: '25g protein per serving. Ultra-pure whey isolate with smooth vanilla flavor.',
  },
  {
    id: 'powder-2',
    name: 'Whey Isolate - Chocolate',
    price: 54.99,
    image: '/products/powder-chocolate.jpg',
    category: 'protein-powder',
    flavor: 'Rich Chocolate',
    weight: '2 lbs',
    rating: 4.8,
    reviews: 3892,
    badge: 'Best Seller',
    description: '25g protein per serving. Decadent chocolate taste that mixes perfectly.',
  },
  {
    id: 'powder-3',
    name: 'Plant Protein Blend',
    price: 49.99,
    image: '/products/powder-plant.jpg',
    category: 'protein-powder',
    flavor: 'Chocolate Peanut',
    weight: '2 lbs',
    rating: 4.7,
    reviews: 1876,
    badge: 'Vegan',
    description: '24g plant protein. Pea, rice, and hemp blend for complete amino profile.',
  },
  {
    id: 'powder-4',
    name: 'Mass Gainer - Cookies',
    price: 64.99,
    image: '/products/powder-mass.jpg',
    category: 'protein-powder',
    flavor: 'Cookies & Cream',
    weight: '5 lbs',
    rating: 4.6,
    reviews: 982,
    description: '50g protein, 1200 calories. Perfect for hard gainers and bulking phases.',
  },

  // Creatine
  {
    id: 'creatine-1',
    name: 'Creatine Monohydrate',
    price: 29.99,
    image: '/products/creatine-mono.jpg',
    category: 'creatine',
    weight: '500g',
    rating: 4.9,
    reviews: 5234,
    badge: 'Best Seller',
    description: 'Pure micronized creatine monohydrate. 5g per serving, 100 servings.',
  },
  {
    id: 'creatine-2',
    name: 'Creatine HCL',
    price: 34.99,
    image: '/products/creatine-hcl.jpg',
    category: 'creatine',
    weight: '120 caps',
    rating: 4.8,
    reviews: 1543,
    badge: 'Premium',
    description: 'Highly soluble creatine HCL. No loading phase required, easy on stomach.',
  },
  {
    id: 'creatine-3',
    name: 'Creatine + ATP Boost',
    price: 44.99,
    image: '/products/creatine-atp.jpg',
    category: 'creatine',
    weight: '300g',
    rating: 4.7,
    reviews: 876,
    badge: 'New Formula',
    description: 'Creatine with ATP precursors for maximum power output and endurance.',
  },
]

export const categories = [
  { id: 'all', name: 'All Products' },
  { id: 'protein-bars', name: 'Protein Bars' },
  { id: 'protein-powder', name: 'Protein Powder' },
  { id: 'creatine', name: 'Creatine' },
]
